name: floraguard
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - appdirs=1.4.4
  - attr=2.5.1
  - attrs=24.2.0
  - automat=24.8.1
  - bcrypt=4.2.0
  - beautifulsoup4=4.12.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cairo=1.18.2
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - constantly=15.1.0
  - cryptography=38.0.2
  - cssselect=1.2.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dbus=1.13.6
  - expat=2.6.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.12.1
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - glib=2.82.2
  - glib-tools=2.82.2
  - graphite2=1.3.13
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - h2=4.1.0
  - harfbuzz=10.2.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - hyperlink=21.0.0
  - icu=75.1
  - idna=3.10
  - incremental=24.7.2
  - itemloaders=1.3.2
  - jmespath=1.0.1
  - joblib=1.4.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcups=2.3.3
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.6
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.25
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.46
  - libpq=17.3
  - libsndfile=1.2.2
  - libsqlite=3.48.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.3
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lxml=4.9.3
  - lz4-c=1.10.0
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mpg123=1.32.9
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - nspr=4.36
  - nss=3.108
  - numpy=1.19.5
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.1
  - packaging=24.2
  - pandas=1.4.4
  - pcre2=10.44
  - pillow=10.4.0
  - pip=24.3.1
  - pixman=0.44.2
  - ply=3.11
  - protego=0.3.1
  - pthread-stubs=0.4
  - pulseaudio-client=17.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pydispatcher=2.0.5
  - pyopenssl=23.2.0
  - pyparsing=3.1.4
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0
  - python_abi=3.8
  - pytz=2024.2
  - qt-main=5.15.15
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=0.22.2.post1
  - scipy=1.5.2
  - scrapy=2.9.0
  - service_identity=24.2.0
  - setuptools=75.3.0
  - sip=6.7.12
  - six=1.16.0
  - soupsieve=2.5
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.2
  - tornado=6.4.1
  - twisted=22.10.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - unicodedata2=15.1.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xorg-libxxf86vm=1.1.6
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - zope.interface=7.0.3
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - autologin-middleware==0.1.6
      - autopager==0.3
      - backports-csv==1.0.7
      - botocore==1.36.22
      - cachetools==5.5.1
      - datasketch==1.6.3
      - demoji==1.1.0
      - docopt==0.6.2
      - emoji==2.8.0
      - filelock==3.12.2
      - formasaurus==0.8.1
      - itemadapter==0.8.0
      - json-lines==0.5.0
      - maybedont==0.1.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - parsel==1.8.1
      - protobuf==5.29.3
      - python-crfsuite==0.9.11
      - queuelib==1.6.2
      - requests-file==1.5.1
      - scrapy-cdr==0.6.0
      - scrapy-splash==0.9.0
      - service-identity==21.1.0
      - sklearn-crfsuite==0.3.6
      - stanza==1.5.1
      - tabulate==0.9.0
      - tldextract==3.5.0
      - torch==1.13.1
      - tqdm==4.67.1
      - urllib3==1.26.16
      - w3lib==2.1.2
