name: floraguard
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - beautifulsoup4=4.12.2
  - numpy=1.19.5
  - scipy=1.5.2
  - pandas=1.4.4
  - scikit-learn=0.22.2
  - matplotlib=3.5.3
  - scrapy=2.9.0
  - twisted=22.10.0
  - cryptography=38.0.2
  - lxml=4.9.3
  - requests=2.31.0
  - pip:
      - autologin-middleware==0.1.6
      - autopager==0.3
      - cssselect==1.2.0
      - datasketch==1.6.3
      - demoji==1.1.0
      - emoji==2.8.0
      - filelock==3.12.2
      - formasaurus==0.8.1
      - hyperlink==21.0.0
      - itemadapter==0.8.0
      - jmespath==1.0.1
      - json-lines==0.5.0
      - maybedont==0.1.1
      - parsel==1.8.1
      - queuelib==1.6.2
      - requests-file==1.5.1
      - scrapy-cdr==0.6.0
      - scrapy-splash==0.9.0
      - service-identity==21.1.0
      - sklearn-crfsuite==0.3.6
      - stanza==1.5.1
      - tabulate==0.9.0
      - tldextract==3.5.0
      - torch==1.13.1
      - urllib3==1.26.16
      - w3lib==2.1.2

